containers widgets ui
SuperdeskWebPublisher/livesite-management pull request #7
Opened 2017-01-25 14:17 UTC by tomaszrondio

not perfect but should be cool enough for start

2017-01-25 15:02 UTC, takeit requested changes
It looks awesome so far! 👍

2017-01-25 15:02 UTC, takeit commented on app/components/containerControls/containerControls.html
> +
not needed new line

2017-01-25 15:02 UTC, takeit commented on app/components/containerControls/containerControls.scss
> +}
new line is missing

2017-01-25 15:02 UTC, takeit commented on app/components/toolbar/toolbar.html
> +<div class="leToolbar" ng-class="{'leToolbar--active': toolbarActive}">
the toolbar is transparent when there is more text and when you scroll down, see below:

<img width="1204" alt="zrzut ekranu 2017-01-25 15 58 35" src="https://cloud.githubusercontent.com/assets/562536/22295467/57847e7c-e317-11e6-9d98-1996e71e70d8.png">

2017-01-25 15:02 UTC, takeit commented on app/components/widgetControls/widgetControls.html
> +
new line not needed

2017-01-25 15:02 UTC, takeit commented on app/components/widgetControls/widgetControls.scss
> +}
new line is missing

2017-01-25 15:02 UTC, takeit commented on app/style/_blockControls.scss
> + }
new line is missing

2017-01-25 15:02 UTC, takeit commented on app/style/app.scss
> +@import '_blockControls';
new line is missing

2017-01-25 15:02 UTC, takeit commented on app/style/_variables.scss
> +$colorWidget: #673ab7;
new line is missing

2017-01-25 15:02 UTC, takeit commented on app/style/_helpers.scss
> +}
new line is missing

2017-01-25 15:02 UTC, takeit commented on app/style/_breakpoints.scss
> +}
new line is missing

2017-01-26 10:22 UTC, pavlovicnemanja approved these changes

2017-01-26 10:34 UTC, takeit approved these changes

2017-01-26 10:39 UTC, merged